apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flasktest
  name: flasktest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasktest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flasktest
    spec:
      containers:
      - image: sadminriley/images:app-6
        name: flasktest
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-service
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 5000
  selector:
    app: flasktest
