apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-service
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 5000
  selector:
    app: flask
